Dimillian/ACHNBrowserUI

ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsListView.swift

This improves the search legibility. Before it was dark and hard to read.

fix: improve search legibility

---

ACHNBrowserUI/ACHNBrowserUI/views/categories/CategoriesView.swift

Before, the Category rows could only be tapped by tapping on the text in the cell. This convert the category cell to a button so the entire row is tappable. It should look the same.

fix: category row is now fully tappable

---

ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsListView.swift

Various improvements to the sort experience:
- When sort is activated the Navigation Bar Item will become filled.
- Changed "Remove Filter" copy to "Clear Selection" since its not really a filter.
- Localized Capitalized should be the preferred capitalization method since it will take in to account use locale.
- The action sheet will now show what the currently selected sort is.
- Hide the "Clear Selection" button is no selection is present.
- Switching sorts is now nearly instant.

feat: improved sort experience

---

ACHNBrowserUI/ACHNBrowserUI/views/items/ItemImage.swift

before, items looked squashed. now they don't!
|                                                                                                                                                            Before |  After                                                                                                                                                            |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------:|-------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ![Simulator Screen Shot - iPhone 11 - 2020-04-16 at 19 13 …

fix: images display correctly

---

ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsListView.swift

When running in split screen, the colors looked off. This adds a placeholder view.

fix: add a split-screen placeholder view

---

ACHNBrowserUI/ACHNBrowserUI/views/collection/CollectionListView.swift

This was an empty screen. Now it gives the user some instruction.

fix: add empty state to the collection screen

---

ACHNBrowserUI/ACHNBrowserUI/Colors.xcassets/text.colorset/Contents.json
ACHNBrowserUI/ACHNBrowserUI/Info.plist
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift

- Status bar should always be white, looks better.
- Made the text color slightly lighter in dark mode so it is easier to read.

fix: force light content in status bar & dark mode fixes

---

ACHNBrowserUI/ACHNBrowserUI/views/shared/SearchField.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift

placeholder was "Search an item" now it is "Search a villager"

fix: proper villager search copy

---

ACHNBrowserUI/ACHNBrowserUI/viewModifiers/DismissingKeyboardOnSwipe.swift

* Previously crashed after doing a search as the ViewModifier
DismissingKeyboardOnSwipe is useless on macOS and call some iOS only
methods under the hood that leads to crash the app.
* Fix #38

fix: lists are working as expected after doing a search on macOS

---

ACHNBrowserUI/ACHNBrowserUI/views/categories/CategoriesView.swift

Finally, I found the problem, thanks to: https://forums.developer.apple.com/thread/122451
I spent so much time that I started to refactor and split the `List` into some tinier ones, so I let the code like this as well (I find it easier to read now).

fix(Categories): avoid crashes by ordering search results

---

ACHNBrowserUI/ACHNBrowserUI/views/about/AboutView.swift

Without this set, the About View modal has a sub-split view which leaves a huge gap on the right side of the modal.

Use a StackNavigationViewStyle to fix About view on iPad

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/extensions/View.swift
ACHNBrowserUI/ACHNBrowserUI/views/about/AboutView.swift
ACHNBrowserUI/ACHNBrowserUI/views/dashboard/DashboardView.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/detail/ItemDetailView.swift
ACHNBrowserUI/ACHNBrowserUI/views/settings/SettingsView.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/LikeButtonView.swift
ACHNBrowserUI/ACHNBrowserUI/views/subscription/SubscribeView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/TurnipsFormView.swift

There are a few tricks in here:
For nav bar items, we need to add in a padding and offset (+ or - depending on which side it appears), stored as a constant in the View extensions file, to simulate the same padding that Apple gives UIKit for free with nav bar button items.
3 new View extensions have been added, though only one is used right now, all prefixed with the word `safe`, eg, `safeHoverEffect`, which takes the same parameters as the normal 13.4+ `safeHover`, `.automatic` (default), `.lift`, or `.highlight` so that the code will run just fine on any >= 13.0 && < 13.4 devices. To not throw a "Symbol Not Found" error, `SwiftUI.framework` needs to be optionally linked into the build phases (thanks to @mike_p3 who makes the Strong app for that tweak!)
Might be worth refactoring the …

Add hoverEffects throughout the app

---

ACHNBrowserUI/ACHNBrowserUI/extensions/View.swift
ACHNBrowserUI/ACHNBrowserUI/views/about/AboutView.swift
ACHNBrowserUI/ACHNBrowserUI/views/dashboard/DashboardView.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/detail/ItemDetailView.swift
ACHNBrowserUI/ACHNBrowserUI/views/settings/SettingsView.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/LikeButtonView.swift
ACHNBrowserUI/ACHNBrowserUI/views/subscription/SubscribeView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/TurnipsFormView.swift

Also has the benefit of consolidating the hoverPadding constant in the
one place where it’s needed. Pass in a position whenever you use this, `.leading` or `.trailing` to match `navigationBarItems`.

Refactor hoverEffect for Bar Items for more concise code + clarity

---

ACHNBrowserUI/ACHNBrowserUI/views/settings/AppIconPickerView.swift
ACHNBrowserUI/ACHNBrowserUI/views/settings/SettingsView.swift

now you can see the selected icon in the app.

feat: show selected alternate app icon

---

ACHNBrowserUI/ACHNBrowserUI/SceneDelegate.swift

Setting the `titleVisibility` of the window makes it so the titlebar that appears by default in Catalyst apps is integrated into the main app window, with the close/minimize/zoom buttons appearing as part of the window itself.

feat: integrate Catalyst titlebar into app window

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/services/LocalizedItemsService.swift

Thanks for your great implementation of #44!
The only edge case I've found is the following:
Let's assume your preferred languages are Dansk, German, English.
Currently iOS will pick German for the UI, but `LocalizedItemService` would pick the unsupported Dansk and would therefore fall back to English.
With this PR both contents and the UI will be displayed in German.

Use first supported preferred language

---

ACHNBrowserUI/ACHNBrowserUI/extensions/View.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartBottomLegendView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartView.swift

- Everything is now done using preferences and anchors.
- Convenient height propagation methods has been added to a view extension to be re-used.

[Update] Feat/turnips chart set sticky vertical legend

---

ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartBottomLegendView.swift

* Add a comment to explain why I rolled back this. It's far from ideal
but as I don't know so much about Anchor Preference, I would take time
to dive deeper into it and come with a concrete solution later on.

fix(Turnips): put back hardocded value for Bottom Legend Height

---

ACHNBrowserUI/ACHNBrowserUI/de.lproj/Localizable.strings

How could I missed them? They even had been inside my first commit of #107

Localization: Added missing fish source to localization

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/ItemsViewModel.swift

Relies on localized comparison for sorting items to correctly handle accents and umlauts.
E.g. in German this will treat `Ä` and `Á` as `A` instead of ordering them after `Z`.
| Before | After |
| --- | --- |
| Umlauts/Accents at the end | Umlauts/accents within their normal variants |
| <img alt="Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-12 at 20 54 49" src="https://user-images.githubusercontent.com/2100336/81733843-eec14100-9492-11ea-91e7-9fc057557cd2.png" width="200"> | <img alt="Simulator Screen Shot - iPhone 11 Pro Max - 2020-05-12 at 20 56 40" src="https://user-images.githubusercontent.com/2100336/81733982-216b3980-9493-11ea-87ca-486483cfdbfc.png" width="200"> |

Sort items using localized comparision

---

ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartValuesView.swift

* Previously, it was the minMax color value because it was on the bottom
of the ZStack. As average capsule color is more readable IMO, we choose
this one

feat(Turnips): use average color for entered displayed values in Chart

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/SceneDelegate.swift
ACHNBrowserUI/ACHNBrowserUI/fr.lproj/Localizable.strings
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/TodaySection.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/services/ACNHApiService.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/utils/AppUserDefault.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/wrappers/UserDefaultWrapper.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/DashboardViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/Sheet.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayBirthdaysSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodaySectionEditView.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodaySectionView.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayTurnipSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayView.swift

Hello, I took a stab at issue #115: Organizing Dashboard Widgets as it seemed like a fun task which you were asking for some help on. You can now check/uncheck the rows and move things around. I added support for saving the state to the user defaults so that it reloads with the app.
The only weirdness was that I needed to wrap everything in another to keep the ForEach stable. I think we could refactor the TodayView to push more data to the model.
I hardcoded the subscribe button to not be removable - but I feel like that decision could be left to you to change.
I'm still learning app development so I'd appreciate constructive feedback if you have it :)
Cheers!

Dashboard: organize widgets

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/TodaySection.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/DashboardViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodaySectionEditView.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodaySectionView.swift

* Sometimes a crash could happen (especially when you try to reorder
Tasks to the first elements in the list)

fix(Dashboard Today Widgets): reorder works without crash

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/extensions/Array.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/VillagersViewModel.swift

Sorting villagers by personality makes it easier to find villagers that hands specific items.

Add sort villagers by personality

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/Item.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ItemsViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsListView.swift

- Added an option to sort Bugs and Fish according to Critterpedia order.
Super useful when updating in-app list with in-game collected critter list for the first time.
- Hide sort options unsupported by current collection.
For example, since critters and fossils can’t be bought, a list sorted by “Buy” would just go blank otherwise.

Critterpedia sorting

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/AppDelegate.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/UserCollection.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/Chore.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/TodaySection.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ChoreFormViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ChoreListViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/TodayChoresSectionViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/chores/ChoreFormView.swift
ACHNBrowserUI/ACHNBrowserUI/views/chores/ChoreListRowView.swift
ACHNBrowserUI/ACHNBrowserUI/views/chores/ChoreListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/Sheet.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayChoresSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodaySectionEditView.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodaySectionView.swift

This commit adds custom Chores and To-Dos to the Dashboard.
This feature complements the Daily Tasks Section. It adds a way for the user to track chores and other actions they have to do when playing. For instance:
- Send a card to a friend
- Build an specific gift to a villager
- Sell scorpions to Flick
- Etc...
Think of it as todo app inside the app :-)

Add Custom Chores and To-Dos

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/VillagersViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagerRowView.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift

When filtering villagers by species or personally, it's hard to tell where the next species and personalities start and end.
This feature helps people sorting villagers by species/personalities when they want to invite villagers to move to the island or visit the camp (using amiibos).
The image below shows the villagers list a) without filter, b) filtered by name, c) filtered by species, and 4) by personality.

Add Description to Villager Row View

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

I added new translations for custom tasks as seen in the French and German file. 
I noticed that this time the file was partially in Spanish.😖 I don't know why. But I restored the Italian strings and corrected some typos. I added also some missing strings.

Add Italian translations for custom tasks

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/DashboardViewModel.swift

Maybe this will never happen, but if we disable / delete a widget from dashboard programmatically it still was in order list. That causes a ui bug.

Remove removed widget from order list

---

ACHNBrowserUI/ACHNBrowserUI/extensions/Text.swift
ACHNBrowserUI/ACHNBrowserUI/views/chores/ChoreListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/collection/CollectionListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/dodocode/DodoCodeFormView.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/MessageView.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/SectionHeaderView.swift
ACHNBrowserUI/ACHNBrowserUI/views/userLists/UserListDetailView.swift

- switched from String to LocalizedStringKey in SectionHeaderView
- overload init from SectionHeaderView to match with init calls where string variables are passed into init
- replaced SectionHeaderView text style modification with style method
- improved MessageView init
- removed unnecessary LocalizedStringKey
- moved collection name translation into init to be more readable

Improved localization handling of MessageView and SectionHeaderView

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/VillagersViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayBirthdaysSection.swift

This PR addresses two issues with the `VillagersViewModel`. In particular with its recreation whenever SwiftUI dictates so and the implicit use of `self` as part of its implementation.
1. Make `self` weak and avoid the `map`'s closure capturing `self`.
2. Use `StateObject` instead of `ObservedObject`. Although I am not particular fond of this approach, it fixes the problem where `VillagersViewModel` is being recreated every time the user switches tab on `TodayBirthdaysSection`.
This problem can be seen here:
| Before | After (with this PR) |
|-------|------|
| ![before](https://user-images.githubusercontent.com/949286/85961619-9511c900-b9a3-11ea-9dfe-d381b955ea03.gif) | ![after](https://user-images.githubusercontent.com/949286/85961656-d2765680-b9a3-11ea-8a9e-84ab5ca59f23.gif) |
We can …

Fix retain cycle and VM recreation

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/ItemsViewModel.swift

#289
The sea creatures should be sorted by critterpedia but not buy, set, or similar.

Limited the sort method for sea creatures (legacy)

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/ItemsViewModel.swift

https://github.com/Dimillian/ACHNBrowserUI/issues/289
The sea creatures should be sorted by critterpedia but not buy, set, or similar.

Limited the sort method for sea creatures

---

ACHNBrowserUI/Widgets/views/VillagerBirthdayWidget.swift

Just some minor syntax changes
`[]` can also be used instead of `RedactionReasons()`
Why was `isPlaceholder()` deprecated 😞

redacted(reason:) syntax tweaks

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/env/CurrentDateEnvironment.swift
ACHNBrowserUI/ACHNBrowserUI/utils/EventsDescription.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ActiveCrittersViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/TabbarViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/critters/ActiveCrittersView.swift
ACHNBrowserUI/ACHNBrowserUI/views/home/TabbarView.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/CalendarView.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayCurrentlyAvailableSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayEventsSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodaySpecialCharactersSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayTurnipSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/TurnipsFormView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartView.swift
ACHNBrowserUI/Packages/Backend/Sources/Backend/Extensions/Collection.swift
ACHNBrowserUI/Packages/Backend/Sources/Backend/Models/Item.swift
ACHNBrowserUI/Packages/Backend/Sources/Backend/Models/SpecialCharacters.swift
ACHNBrowserUI/Packages/Backend/Sources/Backend/Models/Turnips.swift
ACHNBrowserUI/Packages/Backend/Sources/Backend/Services/TurnipPredictionsService.swift
ACHNBrowserUI/Packages/Backend/Tests/BackendTests/CrittersTests.swift

* Fix #325
* Previously the date was only update once the app start. So at some
point if the app survive a night, the date will be wrong. To prevent
that, we update now the date every time the tab is changed

fix: update the current date when changing tabs

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/ItemsViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsView.swift

Nook Phone ignores dashes, "-", when sorting items. This commit ignores dashes when sorting by name or when searching, so that the results match the list in Nook Phone, making it easier to catalog items.
This commit also moves the list ot current items to the view model.
Before and After:

Sort using Nook Phone order

---

ACHNBrowserUI/ACHNBrowserUI/views/critters/ActiveCrittersView.swift

* Previously, the loading of critters was not triggered, so it displayed
an activity indicators without endlessly
* Fix #330

fix(Active Critters): load critters when opening Active Critters View

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/LikeButtonViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/detail/ItemDetailView.swift
ACHNBrowserUI/Packages/Backend/Sources/Backend/Environments/UserCollection.swift

* Previously, tapping the Like button did save the current variation but
the feedback wasn't correct and was only visible after liking another
variation (or potentially doing another action). It was due to the fact we were
manipulating directly the collection (ViewModel) inside the `sink`
callback instead of manipulating the `variations` we received from the
`sink` callback.
* Partially fix #230. Still need to provide a correct feedback about
starring "partially" the item if only some of variations have been
liked. Could be addressed in an another PR.
The bug:
https://user-images.githubusercontent.com/2297556/103180889-2b12a780-4892-11eb-8271-2e3b14727ec5.mov
The fix:
https://user-images.githubusercontent.com/2297556/103180894-36fe6980-4892-11eb-9379-3c84fa560937.mov

fix(Items Variants Like): tap the like button provide correct feedback
