Dimillian/ACHNBrowserUI

ACHNBrowserUI/ACHNBrowserUI/Base.lproj/LaunchScreen.storyboard

so you don't blind yourself opening this at night / smoother transition

fix: use grass color for splash screen

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/Assets.xcassets/icon/icon-bag.imageset/Contents.json
ACHNBrowserUI/ACHNBrowserUI/Assets.xcassets/icon/icon-bells.imageset/Contents.json
ACHNBrowserUI/ACHNBrowserUI/Assets.xcassets/icon/icon-branch.imageset/Contents.json
ACHNBrowserUI/ACHNBrowserUI/Assets.xcassets/icon/icon-helmet.imageset/Contents.json
ACHNBrowserUI/ACHNBrowserUI/Assets.xcassets/icon/icon-leaf-design.imageset/Contents.json
ACHNBrowserUI/ACHNBrowserUI/Assets.xcassets/icon/icon-miles.imageset/Contents.json
ACHNBrowserUI/ACHNBrowserUI/Colors.xcassets/TabLabel.colorset/Contents.json
ACHNBrowserUI/ACHNBrowserUI/SceneDelegate.swift
ACHNBrowserUI/ACHNBrowserUI/models/Listing.swift
ACHNBrowserUI/ACHNBrowserUI/services/ImageService.swift
ACHNBrowserUI/ACHNBrowserUI/services/NookazonService.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ItemDetailViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/collection/CollectionListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/home/TabbarView.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemDetailView.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsListView.swift

This PR aims to add [nookazon](https://nookazon.com) integrations for items! It is not completely fleshed out, as it only display listing info. More could be added.

feat: add nookazon listings

---

ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift

for some reason, it looked quite wonky before.

fix: villager tab shows up correctly

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/models/Island.swift
ACHNBrowserUI/ACHNBrowserUI/services/TurnipExchangeService.swift

This PR implements the service necessary for communicating with [turnip.exchange](https://api.turnip.exchange).
So we can find the best turnip prices! UI and etc will come later.

feat: add turnip exchange service

---

ACHNBrowserUI/ACHNBrowserUI/services/TurnipExchangeService.swift

This uses a pretty dope / hack way to get the listings from turnip.exchange.

fix: turnip listing service actually works!

---

ACHNBrowserUI/ACHNBrowserUI/services/TurnipExchangeService.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/TurnipsView.swift

fix: turnip exchange works again

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/viewModifiers/DismissingKeyboardOnSwipe.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemsListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift

* Previously you had to tap "return" if you want to dismiss the
keyboard

fix(Villagers): Swipe gesture dismiss the keyboard

---

Readme.md

Love the project! I had actually started my own here: https://github.com/jstart/ac-new-horizons-guide
But hoping to contribute to this project!
Also noticed the name of the repo is `ACHN` instead of `ACNH`, but that might be too difficult to change..

Few typos, thanks for the project!

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/VillagersViewModel.swift

* Use `assign` Combine instruction instead of `sink` for instance

refactor(Villagers): improve Combine code of VillagersViewModel

---

Readme.md

🤓
Created with [`readme-correct`](https://github.com/dkhamsing/readme-correct).

Correct typo in README

---

ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChart.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartAverageCurve.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartBottomLegendView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartGrid.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartMinBuyPriceCurve.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartMinMaxCurves.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartVerticalLegend.swift

feat(Turnips): let the chart breath with extra rounded steps

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI.xcodeproj/xcshareddata/xcschemes/ACHNBrowserUI.xcscheme
ACHNBrowserUI/ACHNBrowserUI/AppDelegate.swift
ACHNBrowserUI/ACHNBrowserUI/SceneDelegate.swift
ACHNBrowserUI/ACHNBrowserUI/extensions/Text.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/UserCollection.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/Category.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/Item.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/UserList.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/UserListDetailViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/UserListFormViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/categories/CategoriesView.swift
ACHNBrowserUI/ACHNBrowserUI/views/categories/CategoryHeaderView.swift
ACHNBrowserUI/ACHNBrowserUI/views/collection/CollectionListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemRowView.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/RowLoadingView.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/Sheet.swift
ACHNBrowserUI/ACHNBrowserUI/views/subscription/SubscribeView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/TurnipsView.swift
ACHNBrowserUI/ACHNBrowserUI/views/userLists/UserListDetailView.swift
ACHNBrowserUI/ACHNBrowserUI/views/userLists/UserListFormView.swift
ACHNBrowserUI/ACHNBrowserUI/views/userLists/UserListRow.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift

Add the possibility to create custom lists of items with an icon, title and description. It'll be gated by the subscription.

WIP: User lists

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/UserCollection.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/DashboardViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/dashboard/DashboardCollectionProgressSection.swift

Please be hard at review. First time for me of writing productive SwiftUI code.
I took the leaf as icon placeholder so that should be replaced with a better one.

Added art to collectables on dashboard (fake art is filtered)

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/Items.swift

You know, I'm the fun breaking guy who always wants translated stuff...

Spotlight indexing localized

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/Villager.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/VillagersViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayBirthdaysSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagerDetailView.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagerRowView.swift

Localization of villager detail view (personality and race) will be done in seperate PR because this PR is independent of the Localizable.strings

Use localized villager name if possible

---

ACHNBrowserUI/ACHNBrowserUI/extensions/View.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartBottomLegendView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartVerticalLegend.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartView.swift

Legends now adapt to dynamic type.

Turnip chart's legends size fix

---

Readme.md

- added spotlight
- added localization

Updated features list

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/viewModels/ItemsViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/collection/CollectionListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/collection/CollectionRowView.swift

- Created new CollectionRowView

82 - organize collection tab

---

ACHNBrowserUI/ACHNBrowserUI/de.lproj/Localizable.strings
ACHNBrowserUI/ACHNBrowserUI/views/about/AboutView.swift

- small refactoring
- corrected typo
- added German translation

Bugfix #144 Part 1

---

ACHNBrowserUI/ACHNBrowserUI/fr.lproj/Localizable.strings

Lines update :
38 ,  39 , 40 , 41 , 42 , 43 , 64 , 65 , 77 , 104 , 122 , 225
Add translate description islands

Add translate island and update lines

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI.xcodeproj/xcshareddata/xcschemes/ACHNBrowserUI.xcscheme
ACHNBrowserUI/ACHNBrowserUI/zh-Hans.lproj/Localizable.strings

I have just add some of the simplified Chinese Localisation based on English file.

add zh_cn localize

---

app-store/metada/de.md

Removed english line, added iCloud as a feature

Update App Store description

---

ACHNBrowserUI/ACHNBrowserUI/de.lproj/Localizable.strings

- iCloud translated
- Special visitor times translated

Updated German translation for special visitors

---

ACHNBrowserUI/ACHNBrowserUI/de.lproj/Localizable.strings

Todo: translate what villagers like

WIP: German translation fixes for the next release

---

ACHNBrowserUI/ACHNBrowserUI/de.lproj/Localizable.strings
ACHNBrowserUI/ACHNBrowserUI/fr.lproj/Localizable.strings
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayMusicPlayerSection.swift

Music player goes German

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/fr.lproj/Localizable.strings
ACHNBrowserUI/ACHNBrowserUI/viewModels/VillagersViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersSortView.swift

- Enabling sort options to villagers, according to issue #187 
First time doing a real app in SwiftUI, feel free to give any feedback ;)

Sorting villagers by name or species

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/models/Item.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Tests/BackendTests/CrittersTests.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/ItemRowView.swift

Show 12 or 24 hour time based on user settings. The sell chip takes a lot of space, so this moves the time above it.

feat: 12 hour time based on Locale

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

Fixed some typos and added some missing strings found in the German file.

Fixed Italian language

---

ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayTasksSection.swift

@Dimillian I'm not able to test on a real device due to the mess with Provisioning profile, but for a such tiny change, I would rather ask you if you can quickly test that on your side?
Thanks :)

feat(Today Dashboard - Tasks): add haptic feedback on touch or long press

---

ACHNBrowserUI/ACHNBrowserUI/ja.lproj/InfoPlist.strings
ACHNBrowserUI/ACHNBrowserUI/ja.lproj/Localizable.strings

Add Japanese Localization

---

Readme.md

Not "Mimikun"...
My name is "mimikun"

fix my name

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings
app-store/metada/it.md

I noticed that the App Store metadata weren't translated in Italian. I hope that this can be useful.

Italian App Store metadata

---

ACHNBrowserUI/ACHNBrowserUI/env/MusicPlayerManager.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/Items.swift
ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/UserCollection.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ItemDetailViewModel.swift

`guard let self = self else { return }` is supported since 4.2. Don't need to find a new variable name like "weakself" for this.

replace weakself with self

---

ACHNBrowserUI/ACHNBrowserUI/views/chores/ChoreFormView.swift
ACHNBrowserUI/ACHNBrowserUI/views/design/DesignFormView.swift
ACHNBrowserUI/ACHNBrowserUI/views/settings/SettingsView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/TurnipsFormView.swift
ACHNBrowserUI/ACHNBrowserUI/views/userLists/UserListFormView.swift

Added TextField alignment (trailing) to give input fields in form views a more natural user experience.

More natural looking TextFields in Form Views

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/UserCollection.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ChoreFormViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ChoreListViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/chores/ChoreListView.swift

Allow editing chores (title and description)

Add Chore Editing

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/UserCollection.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/DesignFormViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/design/DesignListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/design/DesignRowView.swift

Allows editing designs (title, code, and description).

Add Creators and Custom Designs Editing

---

ACHNBrowserUI/ACHNBrowserUI/views/customTasks/CustomTaskFormView.swift

UX of free Input field was really worse.

Custom Tasks: replace amount input field with number picker

---

ACHNBrowserUI/ACHNBrowserUI/views/shared/CalendarView.swift

Automatic localized short month name for critter detail view

---

ACHNBrowserUI/ACHNBrowserUI/views/collection/CollectionListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/critters/ActiveCrittersView.swift
ACHNBrowserUI/ACHNBrowserUI/views/musicPlayer/PlayerView.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift

I added swipe gestures on:
- music player (next / previous song)
- active critter list (switch between fish and bugs)
- villager list (switch between all, liked, residents)
- collection list (switch between items, lists, more)

Swipe gestures

---

ACHNBrowserUI/ACHNBrowserUI/packages/Backend/Sources/Backend/environments/UserCollection.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/ChoreListViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/chores/ChoreListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/design/DesignListView.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayChoresSection.swift

and match navigation bar style with other parts of the app.

Show/Hide Finished Chores

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

New strings added for villager visits.
Some typos fixed, especially "Wedding season" not correctly translated in the Events section.

Update to Italian translation

---

ACHNBrowserUI/ACHNBrowserUI/views/design/DesignRowView.swift

Improve Design Code Readability

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

Added some missing strings too. Minor text fixes for better understandable words.

Added Dodo code translations

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/DashboardViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodaySectionEditView.swift

Added small reset button for section ordering

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

Translated new strings for Dodo Code notification.

Update to Italian translation of Dodo Code

---

ACHNBrowserUI/ACHNBrowserUI.xcodeproj/project.pbxproj
ACHNBrowserUI/ACHNBrowserUI/extensions/Sequence+Unique.swift
ACHNBrowserUI/ACHNBrowserUI/representables/ActivityControllerView.swift
ACHNBrowserUI/ACHNBrowserUI/viewModels/VillagerDetailViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/items/detail/ItemDetailSource.swift
ACHNBrowserUI/ACHNBrowserUI/views/shared/Sheet.swift

* When trying to work on #251, but cannot fix the initial issue. At
least these improvements can be merged
I tried so hard this morning to tackle this issue... I can't figure it out as well.
I just changed some code here and there to try but at least it's already a tiny improvement.
The crash message is really not helpful.

refactor(Share): improve code of sharing feature

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

New strings translated for Dodo code comments.
Fixes.

Updated Italian localization for Dodo code comments

---

ACHNBrowserUI/ACHNBrowserUI/fr.lproj/Localizable.strings

Because I die inside when I see it in the app :)
Great job!

Fixed typo in french shadow size

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

New strings added for the news section and dodo comments.
Fixed some uppercase/lowercase characters.

Updated Italian localization

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

Added Sea Creatures and some missing strings.

Update to Italian translations

---

ACHNBrowserUI/ACHNBrowserUI/fr.lproj/Localizable.strings

Ajout de plusieurs éléments traduit en Français.

Ajout de traductions Fr (legacy)

---

ACHNBrowserUI/ACHNBrowserUI/fr.lproj/Localizable.strings

Ajout de plusieurs éléments traduit en Français.

Ajout de traductions Fr (beta xcode 12)

---

ACHNBrowserUI/ACHNBrowserUI/it.lproj/Localizable.strings

New strings for the Summer Patch added.

Fixed Italian localization

---

ACHNBrowserUI/ACHNBrowserUI/es.lproj/Localizable.strings

- new strings translated spanish
- improvement of some Spanish strings
- Spanish archive organization with comments

organization and new translations for Spanish language

---

ACHNBrowserUI/ACHNBrowserUI/de.lproj/Localizable.strings

Please merge to legacy and main

Dream Code sort localization

---

.github/workflows/xcodebuild.yml
ACHNBrowserUI/Packages/UI/.swiftpm/xcode/xcshareddata/xcschemes/UI.xcscheme

* Also use Xcode to build and test Libraries such as Backend or UI as
they need WidgetKit to be builded and tested now
* Update UI Scheme to add UITests as Target

fix(CI): move to Xcode 12 and use explicit iOS 14.0 version

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/ActiveCrittersViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/critters/ActiveCrittersView.swift

* Previously it displayed a Loading View
* Fix #321

fix(View Active Critters): display all lists when all have been captured

---

privacy-policy.md

Replace "dislay" with "display"

Fix typo in privacy policy

---

ACHNBrowserUI/ACHNBrowserUI/extensions/View.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartBottomLegendView.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartVerticalLegend.swift
ACHNBrowserUI/ACHNBrowserUI/views/turnips/charts/TurnipsChartView.swift

Nice work on adding a bit of ergonomics to the preferences @Pyroh 👏
I improved the API a bit (I hope so 😅) and eliminated some repeated code.
What do you think?

Dry up the dance around preferences a bit

---

ACHNBrowserUI/ACHNBrowserUI/viewModels/VillagersViewModel.swift
ACHNBrowserUI/ACHNBrowserUI/views/todayDashboard/TodayBirthdaysSection.swift
ACHNBrowserUI/ACHNBrowserUI/views/villagers/VillagersListView.swift

fix(Today Birthdays): handle when there is no birthday this day
